-- MySQL Script generated by MySQL Workbench
-- Thu Jun  5 11:42:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SocialPet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SocialPet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SocialPet` DEFAULT CHARACTER SET utf8 ;
USE `SocialPet` ;

-- -----------------------------------------------------
-- Table `SocialPet`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(90) NOT NULL,
  `email_usuario` VARCHAR(100) NOT NULL,
  `senha_hash` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_usuario_UNIQUE` (`email_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`raca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`raca` (
  `id_raca` INT NOT NULL,
  `nome_raca` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id_raca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`especie` (
  `id_especie` INT NOT NULL,
  `nome_especie` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id_especie`),
  UNIQUE INDEX `nome_especie_UNIQUE` (`nome_especie` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`pet` (
  `id_pet` INT NOT NULL,
  `nome_pet` VARCHAR(45) NOT NULL,
  `data_nasc` DATETIME NOT NULL,
  `foto_pet` VARCHAR(255) NULL,
  `id_usuario` INT NOT NULL,
  `id_raca` INT NOT NULL,
  `id_especie` INT NOT NULL,
  PRIMARY KEY (`id_pet`),
  INDEX `fk_pet_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_pet_raca1_idx` (`id_raca` ASC) VISIBLE,
  INDEX `fk_pet_especie1_idx` (`id_especie` ASC) VISIBLE,
  CONSTRAINT `fk_pet_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `SocialPet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_raca1`
    FOREIGN KEY (`id_raca`)
    REFERENCES `SocialPet`.`raca` (`id_raca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_especie1`
    FOREIGN KEY (`id_especie`)
    REFERENCES `SocialPet`.`especie` (`id_especie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`post` (
  `id_post` INT NOT NULL,
  `img_post` VARCHAR(255) NOT NULL,
  `legenda_post` VARCHAR(255) NOT NULL,
  `data_post` DATETIME NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_post_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `id_post_UNIQUE` (`id_post` ASC) VISIBLE,
  CONSTRAINT `fk_post_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `SocialPet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`curtida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`curtida` (
  `id_curtida` INT NOT NULL,
  `data_curt` DATETIME NOT NULL,
  `id_post` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_curtida`),
  INDEX `fk_curtida_post1_idx` (`id_post` ASC) VISIBLE,
  UNIQUE INDEX `id_curtida_UNIQUE` (`id_curtida` ASC) VISIBLE,
  INDEX `fk_curtida_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_curtida_post1`
    FOREIGN KEY (`id_post`)
    REFERENCES `SocialPet`.`post` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curtida_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `SocialPet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`comentario` (
  `id_comentario` INT NOT NULL,
  `texto_comen` TEXT(300) NOT NULL,
  `data_comen` DATETIME NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_post` INT NOT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_comentario_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_comentario_post1_idx` (`id_post` ASC) VISIBLE,
  CONSTRAINT `fk_comentario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `SocialPet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_post1`
    FOREIGN KEY (`id_post`)
    REFERENCES `SocialPet`.`post` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`market`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`market` (
  `id_market` INT NOT NULL,
  `nome_market` VARCHAR(100) NOT NULL,
  `tipo_market` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_market`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`produto` (
  `id_produto` INT NOT NULL,
  `nome_produto` VARCHAR(45) NOT NULL,
  `preco_produto` DECIMAL(10,2) NOT NULL,
  `estoque_produto` INT NOT NULL,
  `id_market` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_produto_market1_idx` (`id_market` ASC) VISIBLE,
  CONSTRAINT `fk_produto_market1`
    FOREIGN KEY (`id_market`)
    REFERENCES `SocialPet`.`market` (`id_market`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`compra` (
  `id_compra` INT NOT NULL,
  `qtd_compra` INT NOT NULL,
  `data_compra` DATETIME NOT NULL,
  `status_compra` ENUM('Aprovado', 'Enviado', 'Entregue', 'Pendente', 'Concluida', 'Cancelada') NULL,
  `id_usuario` INT NOT NULL,
  `id_produto` INT NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_compra_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_compra_produto1_idx` (`id_produto` ASC) VISIBLE,
  UNIQUE INDEX `id_compra_UNIQUE` (`id_compra` ASC) VISIBLE,
  CONSTRAINT `fk_compra_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `SocialPet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `SocialPet`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`ong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`ong` (
  `id_ong` INT NOT NULL,
  `nome_ong` VARCHAR(45) NOT NULL,
  `tel_ong` VARCHAR(20) NOT NULL,
  `email_ong` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_ong`),
  UNIQUE INDEX `email.ong_UNIQUE` (`email_ong` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`tipo_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`tipo_perfil` (
  `id_tipo_perfil` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo_perfil` ENUM('Pet', 'Ong', 'Empresa', 'Clinica Veterinaria', 'Petshop', 'Veterinario') NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_tipo_perfil`),
  INDEX `fk_tipo_perfil_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_perfil_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `SocialPet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`clinica_veterinaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`clinica_veterinaria` (
  `id_clinica_veterinaria` INT NOT NULL AUTO_INCREMENT,
  `nome_clinica` VARCHAR(100) NOT NULL,
  `endereco_clinica` VARCHAR(255) NOT NULL,
  `telefone_clinica` VARCHAR(20) NOT NULL,
  `email_clinica` VARCHAR(100) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_clinica_veterinaria`),
  INDEX `fk_clinica_veterinaria_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_clinica_veterinaria_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `SocialPet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`veterinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`veterinario` (
  `id_veterinario` INT NOT NULL AUTO_INCREMENT,
  `nome_veterinario` VARCHAR(100) NOT NULL,
  `crm_vet` VARCHAR(30) NOT NULL,
  `especialidade` VARCHAR(100) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_veterinario`),
  UNIQUE INDEX `crm_vet_UNIQUE` (`crm_vet` ASC) VISIBLE,
  INDEX `fk_veterinario_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_veterinario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `SocialPet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`petshop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`petshop` (
  `id_petshop` INT NOT NULL AUTO_INCREMENT,
  `nome_petshop` VARCHAR(100) NOT NULL,
  `telefone_petshop` VARCHAR(20) NOT NULL,
  `email_petshop` VARCHAR(100) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_petshop`),
  INDEX `fk_petshop_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_petshop_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `SocialPet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nome_empresa` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(20) NOT NULL,
  `email_empresa` VARCHAR(100) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  INDEX `fk_empresa_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `SocialPet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocialPet`.`usuario_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocialPet`.`usuario_perfil` (
  `id_usuario_perfil` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_perfil` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario_perfil`),
  INDEX `fk_usuario_perfil_tipo_perfil1_idx` (`id_tipo_perfil` ASC) VISIBLE,
  INDEX `fk_usuario_perfil_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_perfil_tipo_perfil1`
    FOREIGN KEY (`id_tipo_perfil`)
    REFERENCES `SocialPet`.`tipo_perfil` (`id_tipo_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_perfil_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `SocialPet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
